# Generated by Django 3.2.7 on 2023-07-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=52)),
                ('continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica'), ('South America', 'South America')], default='Asia', max_length=13)),
                ('region', models.CharField(max_length=26)),
                ('surface_area', models.FloatField(default=0.0)),
                ('indep_year', models.SmallIntegerField(null=True)),
                ('population', models.IntegerField(default=0)),
                ('life_expectancy', models.FloatField(null=True)),
                ('gnp', models.FloatField(null=True)),
                ('gnp_old', models.FloatField(null=True)),
                ('local_name', models.CharField(max_length=45)),
                ('government_form', models.CharField(max_length=45)),
                ('head_of_state', models.CharField(max_length=60, null=True)),
                ('capital', models.IntegerField(null=True)),
                ('code2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('language', models.CharField(max_length=30)),
                ('is_official', models.CharField(choices=[('T', 'T'), ('F', 'F')], default='F', max_length=1)),
                ('percentage', models.FloatField(default=0.0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchworld.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('country_code', models.CharField(max_length=3)),
                ('district', models.CharField(max_length=20)),
                ('population', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchworld.country')),
            ],
        ),
    ]
