# Generated by Django 3.2.7 on 2023-07-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchworld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='countrylanguage',
            name='country',
        ),
        migrations.RemoveField(
            model_name='countrylanguage',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchworld.country'),
        ),
        migrations.AlterField(
            model_name='countrylanguage',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='searchworld.country'),
        ),
    ]
