# Generated by Django 3.2.7 on 2023-07-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchworld', '0003_countrylanguage_ux01_country_langauge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryLanguage',
        ),
    ]
