# Generated by Django 3.2.7 on 2023-07-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchworld', '0005_auto_20230716_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryLanguage',
        ),
    ]
